### ISSUE TITLE
[issue] can not install in VSCODE

### ISSUE THREAD

**Issue by zhongqingsong** [Helixform/CodeCursor#10]
When I try to install the plugin, Vscode prompts me with this error, What this picture means is
The "ktiays.aicursor" extension cannot be installed because it is not compatible with the current Visual Studio Code version (version 1.70.0).

![Snipaste_2023-03-28_17-02-37](https://user-images.githubusercontent.com/35858818/228186048-d2330904-6ca4-4b11-b62b-a87121c6433a.png)

**Comment by ktiays** [comment]
The extension has only been tested on VSCode version 1.76.0 and above, so we currently do not support lower versions. You can try upgrading VSCode to the latest version before installing the extension.

**Comment by zhongqingsong** [comment]
> The extension has only been tested on VSCode version 1.76.0 and above, so we currently do not support lower versions. You can try upgrading VSCode to the latest version before installing the extension.

oh ,no, My VScode cannot be updated!!! I've reinstalled it several times, No wonder the prompt version is incompatible.
Anyway thanks a lot.
