### ISSUE TITLE
The insertion and replacement methods seem to have some minor issues, as some code is missing.

### ISSUE THREAD

**Issue by zhoufenfens** [Helixform/CodeCursor#11]
Thank you for creating this plugin, it is amazing. However, I have encountered an issue while using it, which is that the replace function sometimes loses some variables. I'm not sure what the cause is.
for example, I want to write a function that generates random numbers.
<img width="354" alt="image" src="https://user-images.githubusercontent.com/3303836/228430965-6e795a2a-cf0c-4d2e-9bc1-e64235ab347c.png">
When the "Insert" and "Replace" buttons are clicked, the code inside the editor will change like this.
<img width="461" alt="image" src="https://user-images.githubusercontent.com/3303836/228431121-ca524262-24d5-4454-9b41-02898a97d9e5.png">
The variables 'timestamp' and 'randomNumber' are missing.

**Comment by unixzii** [comment]
I guess `${}` has some special meanings in the API we use. Thank you for pointing this out, we will have a check.
