### ISSUE TITLE
Can't see the generate code option.

### ISSUE THREAD

**Issue by MaxwellWei** [Helixform/CodeCursor#17]
When I open the command palette and search for "codecursor", the only options I see are

- View: Show CodeCursor
- CodeCursor: Focus on Chat View
- CodeCursor: Reset Chat

There is no "Code Cursor: Generate Code" as in the picture shown in README.

**Comment by LiuCH4NG** [comment]
+1

**Comment by MaxwellWei** [comment]
> Hi @MaxwellWei, "Generate Code" command requires an active text editor. Did you attempt to do it without opening any files?

Yes, I tried searching for this command while opening a JS and a TS file. I also tried installing the Cursor app and then restarting VSCode. Then I tried reinstalling the extension, but still not work.

**Comment by LiuCH4NG** [comment]
After upgrading to 0.3.1, the issue occurred, and after rolling back to 0.3.0, the function resumed normal.

**Comment by MaxwellWei** [comment]
> After upgrading to 0.3.1, the issue occurred, and after rolling back to 0.3.0, the function resumed normal.

Yes, downgrading to 0.3.0 solved the issue.

**Comment by unixzii** [comment]
When I opened the command palette, the command was actually listed there. But when I search for something, it disappeared:
<img width="868" alt="image" src="https://user-images.githubusercontent.com/3109144/228786384-11e01c2e-f738-4f57-a010-5f93206fe614.png">

I guess commit https://github.com/Helixform/CodeCursor/commit/1d0568b930cefe0a01cd1de5aadbb1d5f680534e caused this problem. These commands are controlled by `editorFocus` context value, as the code shows:
```json
{
    "command": "aicursor.generateCode",
    "title": "Generate Code",
    "enablement": "editorFocus",
    "category": "CodeCursor"
}
```
That is to say, when `editorFocus` is `false` (no editors have focus), the commands are disabled. Just before opening the command palette, `editorFocus` is indeed `true`. However, when the command palette opened, the value changed to `false`. And when you type in the search field, VSCode reloads the command list, making these commands disappear.

This is a regression, we will fix it soon.

**Comment by unixzii** [comment]
As a workaround, you can bind keyboard shortcuts to these commands, and invoke them without moving focus off the editor.
