### ISSUE TITLE
Chat deprecation notice

### ISSUE THREAD

**Issue by JokerQyou** [Helixform/CodeCursor#21]
When chatting about selected content, a prefixed notice appeared. It only starts today.

> You are on an old version of Cursor that will be deprecated soon. Please download the latest version at [cursor.so](https://cursor.so/) to get new features and continued support.

<img width="489" alt="image" src="https://user-images.githubusercontent.com/1465267/229141144-e3657e87-079f-42ea-8f53-7c223139f8d9.png">

Also, when asking a new question in the same chat, it would repetitively answer all previous questions before replying to the new question. Is that how Cursor work or a bug in this extension?

**Comment by unixzii** [comment]
Hi @JokerQyou, this situation starts from today. Unfortunately, the Cursor server changes too rapidly and we didn't expect this will happen too soon. Like the notice said, the old API endpoints will be deprecated soon, and the extension will stop working at the meantime. Before we release a new version, you can set your own OpenAI API key to continue using it without limitations.

**Comment by LianguangXue** [comment]
I also face the same problem. I asked to continue writing the answer but not work.

**Comment by yangxianzhe** [comment]
你好，这个的回复可以改成中文吗，即使我用中文去提问，给我的回复依旧是英文。

**Comment by loop1223** [comment]
> 你好，这个的回复可以改成中文吗，即使我用中文去提问，给我的回复依旧是英文。

可以在问题后加answer with chinese，不过这插件可能不会继续更新，官方cursor更换了类似VS Code框架，直接支持VS Code插件市场，可以试试看

**Comment by ktiays** [comment]
Fix in #29.
