### ISSUE TITLE
"Reset Chat" is disabled when the extension is placed in panel

### ISSUE THREAD

**Issue by Alecton4** [Helixform/CodeCursor#22]
I want to move the extension from *Activity Bar* to *Panel* for a wider view. But the "Reest Chat" button is greyed out there. It is normal when placed back to *Activity Bar*. 

My environment:
- extension version: 0.3.2
- VSCode version: 1.77.0
- system: openSUSE Tumbleweed 20230322

The screenshot is as below:

![image](https://user-images.githubusercontent.com/43232804/230619993-8c919042-200f-4fa1-8128-f30e49c0787e.png)

**Comment by ktiays** [comment]
This is indeed a scenario that we did not consider, and we will fix it.

**Comment by ktiays** [comment]
The issue has been fixed in the latest version of the extension.
