### ISSUE TITLE
Lower the required version to 1.73

### ISSUE THREAD

**Issue by albert-ying** [Helixform/CodeCursor#26]
Hi, currently the extension requires a higher version of vscode.

There are many users currently stays in 1.73 due to the custom-UI issue. Would it be possible to lower this version requirement? Thanks!

**Comment by ktiays** [comment]
VSCode has significant API differences in each version.Due to interface incompatibility, our extension currently cannot run properly on VSCode versions below 1.74.0, and we do not have plans to make it compatible with lower versions of VSCode at the moment.
