### ISSUE TITLE
Malfunction: You are on an old version of Cursor that will be deprecated soon...(Response interrupted)

### ISSUE THREAD

**Issue by tungtung423** [Helixform/CodeCursor#27]
I am using the chat function of codecursor in vscode these days. but today the chat function just report the warning as title of this issue, without any answer for my question. I wonder whether the codecursor can function well now, and whether there is any solution to this issue.

**Comment by ghbtest** [comment]
same problem here. the error message says, "You are on an old version of Cursor that will be deprecated soon. Please download the latest version at [cursor.so](https://cursor.so/) to get new features and continued support." please share how to update.

**Comment by ktiays** [comment]
Fix in #29.
