### ISSUE TITLE
there has been no response when I input questions since yesterday

### ISSUE THREAD

**Issue by zhoufenfens** [Helixform/CodeCursor#29]
Since yesterday, there has been no response when I input questions. I don't know if it's a network problem or not. I also haven't seen any place where I can view the logs.

**Comment by 4rt3mi5** [comment]
I also found this issue, which seems to be related to the API change of Cursor.

**Comment by xtremforce** [comment]
Same here.

**Comment by Atomadeus** [comment]
me too.

**Comment by ktiays** [comment]
We have already taken down the old API method and added support for logging in with Cursor accounts. Updating to the latest version can solve this problem. For more information, please refer to #30.

**Comment by FITZET** [comment]
I still can‘t get any outputs today (my version is 0.4.0), please help me (cry)

**Comment by ktiays** [comment]
> I still can‘t get any outputs today (my version is 0.4.0), please help me (cry)

You can try upgrading the extension to the latest version. Our current latest version is `v0.5.1`.

**Comment by FITZET** [comment]
> > I still can‘t get any outputs today (my version is 0.4.0), please help me (cry)
> 
> You can try upgrading the extension to the latest version. Our current latest version is `v0.5.1`.

Thanks
