### ISSUE TITLE
Code-server

### ISSUE THREAD

**Issue by 2253856133** [Helixform/CodeCursor#3]
Can it be used on code-server?

**Comment by KeiKinn** [comment]
My code-sever version is 1.72 and the extension cannot be found in Marketplace. I downloaded the vsix file and it also cannot be installed because the extension only supports version 1.74

**Comment by 2253856133** [comment]
Same

**Comment by ipfans** [comment]
Code-server is using https://open-vsx.org/. I think just uploading a copy to https://open-vsx.org/ is enough.

**Comment by ktiays** [comment]
We will validate the extension on code-server in the future. Once it's confirmed to be working fine, we will release it on Open VSX marketplace.

**Comment by zthxxx** [comment]
me too

```
Unable to install extension 'ktiays.aicursor' as it is not compatible with VS Code '1.74.2'.
```

**Comment by ktiays** [comment]
The extension has been published on [open-vsx.org](https://open-vsx.org/), and the minimum supported version of VSCode has been lowered to `1.74.0`. You can download the [latest version](https://github.com/Helixform/CodeCursor/releases) of the extension to use it on a lower version of VSCode.
