### ISSUE TITLE
0.4.0 (Response interrupted)

### ISSUE THREAD

**Issue by dev-celvin** [Helixform/CodeCursor#33]

**Comment by ktiays** [comment]
You need to log in to your Cursor account or provide your own API Key in order to use the chat function. You can find the login command in the command palette of VSCode.

**Comment by GitHdu** [comment]
version 0.5.1

it reminds that you have already loggin in, but still response interruped

**Comment by dev-celvin** [comment]
> > version 0.5.1
> > it reminds that you have already loggin in, but still response interruped
> 
> You should be able to find the error log in the output panel of VSCode. If you see it, could you please provide it? ![image](https://user-images.githubusercontent.com/44366293/233604954-fc8a716b-0ab4-4684-a84b-9b0f84fcb3c2.png)

In version 0.4.0, I fixed this issue by adding code that triggers a login window to pop up when the response status code is 401 in conversation/mod.rs. I also removed the login status detection code from the sign_in function in authmod.rs. Perhaps this issue is caused by cursor outside of this plugin that has already logged in, such as the cursor app, which may prevent the plugin from obtaining the correct access token.

**Comment by GitHdu** [comment]
> > version 0.5.1
> > it reminds that you have already loggin in, but still response interruped
> 
> You should be able to find the error log in the output panel of VSCode. If you see it, could you please provide it? ![image](https://user-images.githubusercontent.com/44366293/233604954-fc8a716b-0ab4-4684-a84b-9b0f84fcb3c2.png)

<img width="1601" alt="Snipaste_2023-04-23_10-54-38" src="https://user-images.githubusercontent.com/15519616/233817080-4d83f977-d0ff-4929-b882-0a4f5d20bc2a.png">

**Comment by ktiays** [comment]
> > > version 0.5.1
> > > it reminds that you have already loggin in, but still response interruped
> > 
> > 
> > You should be able to find the error log in the output panel of VSCode. If you see it, could you please provide it? ![image](https://user-images.githubusercontent.com/44366293/233604954-fc8a716b-0ab4-4684-a84b-9b0f84fcb3c2.png)
> 
> <img alt="Snipaste_2023-04-23_10-54-38" width="1601" src="https://user-images.githubusercontent.com/15519616/233817080-4d83f977-d0ff-4929-b882-0a4f5d20bc2a.png">

This appears to be because the server returned a 401 error, which may be due to your login information expiring or other reasons that prevent you from using it. Our extension temporarily does not handle this exception, so you can try logging out and then logging back in again. We will follow up on this issue.

**Comment by GitHdu** [comment]
> > > > version 0.5.1
> > > > it reminds that you have already loggin in, but still response interruped
> > > 
> > > 
> > > You should be able to find the error log in the output panel of VSCode. If you see it, could you please provide it? ![image](https://user-images.githubusercontent.com/44366293/233604954-fc8a716b-0ab4-4684-a84b-9b0f84fcb3c2.png)
> > 
> > 
> > <img alt="Snipaste_2023-04-23_10-54-38" width="1601" src="https://user-images.githubusercontent.com/15519616/233817080-4d83f977-d0ff-4929-b882-0a4f5d20bc2a.png">
> 
> This appears to be because the server returned a 401 error, which may be due to your login information expiring or other reasons that prevent you from using it. Our extension temporarily does not handle this exception, so you can try logging out and then logging back in again. We will follow up on this issue.

sign out first, then log in works

**Comment by adndyxu** [comment]
> > > > > version 0.5.1
> > > > > it reminds that you have already loggin in, but still response interruped
> > > > 
> > > > 
> > > > You should be able to find the error log in the output panel of VSCode. If you see it, could you please provide it? ![image](https://user-images.githubusercontent.com/44366293/233604954-fc8a716b-0ab4-4684-a84b-9b0f84fcb3c2.png)
> > > 
> > > 
> > > <img alt="Snipaste_2023-04-23_10-54-38" width="1601" src="https://user-images.githubusercontent.com/15519616/233817080-4d83f977-d0ff-4929-b882-0a4f5d20bc2a.png">
> > 
> > 
> > This appears to be because the server returned a 401 error, which may be due to your login information expiring or other reasons that prevent you from using it. Our extension temporarily does not handle this exception, so you can try logging out and then logging back in again. We will follow up on this issue.
> 
> sign out first, then log in works
How to relogin? , I doesn't see the login function, just set the apikey in settings
