### ISSUE TITLE
can't sign in

### ISSUE THREAD

**Issue by AdorableLi** [Helixform/CodeCursor#34]
even if I successfully sign in to the page, the plugin still displays "Waiting for sign in/sign up..."

**Comment by ktiays** [comment]
This may be due to invalid parameters passed to the webpage. You can try canceling the task and retrying it. We will continue to follow up on this issue.

**Comment by wangxiaodong1021** [comment]
The same problem

**Comment by ktiays** [comment]
This is indeed a bug, and we have fixed it in the latest version. Please update your extension to the latest version.

**Comment by AdorableLi** [comment]
the bug has been fixed, thank you for your work～
