### ISSUE TITLE
What context is passed to the model?

### ISSUE THREAD

**Issue by tonydavis629** [Helixform/CodeCursor#37]
I'm loving CodeCursor. I am having a hard time understanding what exactly is getting passed to the model when I click `Ask`. 

It seems that sometimes, the entire active file is passed as context, and sometimes only half the file. Is there any capability to have context from multiple files? Or a whole project?

I notice that my active selections are also passed. Is there any other context that is passed when I have an active selection? What is that logic? 

Maybe it can be added to the readme, as it's important information to know how to use this.

**Comment by zhangzhuang15** [comment]
Why are you so interested in the context ? Bring you unexpected response ?

I take a quick look at the source code, and only offer you these message according your Question:
1. pass the entire active file as context, not whole project;
2. active selections always should be passed, maybe follow the Cursor App action in this way;
3. the text before and after your selection also will be passed;
4. sometimes only half the file will be passed is not a normal action, may be a bug of CodeCursor or vscode API, you should provide more message, such as screenshot, http response and etc.

From my perspective, it's not necessary  to add these message to the readme, it doesn't block people using CodeCursor, but I feel it's better to make a new manual handbook in this project, put these message into this file.

I hope this could help you.

If your confusion is resolved, please close this question, thank you.

**Comment by tonydavis629** [comment]
Knowing the information that was passed to the model is important to know what questions I can ask it. It is still not clear to me exactly what is passed. There is likely a size limit when asking questions on an entire file, what is that size limit?

**Comment by tonydavis629** [comment]
Unlikely, considering the context length of GPT4 is 8000 tokens.

**Comment by zhangzhuang15** [comment]
To tell the truth, I didn't know the context length of GPT4 before, now I know, but it's redundant for me. In my daily work, I usually use at most 300 tokens. 

This plugin is based on Cursor App, so if you want to get more information about the context length and other limits, I think you'd better ask the maintainer of Cursor App.

**Comment by unixzii** [comment]
Hi @tonydavis629, currently we don't have any idea how Cursor processes your inputs. The API request will encapsulate the whole document of your active tab and the selection (if any). They are sent to Cursor server as is along with your prompts. For more model-related questions, I would suggest you file an issue in <https://github.com/getcursor/cursor>. Thanks for your supports.
