### ISSUE TITLE
could not sign  in vs code

### ISSUE THREAD

**Issue by LongwayCHOW** [Helixform/CodeCursor#38]

**Comment by zhangzhuang15** [comment]
same as [bug#35](https://github.com/Helixform/CodeCursor/issues/35), please close this issue.

There is one temporary solution you can try:
1. clone this [repo](https://github.com/zhangzhuang15/CodeCursor) to your local;
2. switch to the `temporary-use` branch, and following the `SOLUTION.md`;

Just remember that this is just temporary solution! When CodeCursor plugin updates, please come back to use it.
