### ISSUE TITLE
Response interrupted

### ISSUE THREAD

**Issue by tonydavis629** [Helixform/CodeCursor#39]
I am getting a (Response interrupted) error for all requests. I confirm my API key works and OpenAI is not down. The extension has become unusable :(

**Comment by ktiays** [comment]
This is due to significant changes in the Cursor API, and we have migrated the extension to the nearest API. Updating your extension to the latest version will solve the problem.

**Comment by tonydavis629** [comment]
Awesome work, works way better now. Best OpenAI extension available!
