### ISSUE TITLE
Azure OpenAI API 

### ISSUE THREAD

**Issue by colin4k** [Helixform/CodeCursor#41]
Can I use the Azure OpenAI API Key?

**Comment by zhangzhuang15** [comment]
I guess you can't.You can paste your Azure OpenAI API Key to Cursor App which you can download from their official website, if it works, you can use it.

**Comment by colin4k** [comment]
> I guess you can't.You can paste your Azure OpenAI API Key to Cursor App which you can download from their official website, if it works, you can use it.

I can use it now by using a cloudflare worker to transfer openai api requests to azure openai requests.

**Comment by ktiays** [comment]
Cursor currently does not support the use of Azure API Key, so we are unable to provide this capability.

**Comment by vishhvak** [comment]
Hi, anyway this can be done now? Cursor does support Azure OpenAI keys currently, right?
