### ISSUE TITLE
aways failed perform

### ISSUE THREAD

**Issue by taoisym** [Helixform/CodeCursor#7]
<img width="442" alt="image" src="https://user-images.githubusercontent.com/23164750/227771579-4163ff9b-f4a8-483e-866d-0f7448f563e5.png">

**Comment by cleardusk** [comment]
Failed to generate code now. +1
VSCode 1.67.2, the newest CodeCursor from the extention marketplace.

**Comment by ktiays** [comment]
The server of the Cursor is down, which is not a problem with our extension. Please be patient and wait for the Cursor's server to recover.
