### ISSUE TITLE
[Feature]Add a shortcut to apply differences that has same ability like "Accept" button.

### ISSUE THREAD

**Issue by Lirui-Zhao** [Helixform/CodeCursor#9]
Hi,
Sometimes the "Accept" button notification is missed when I click something else, and it's a little bit tedious to use the mouse to click it.
So I hope it can be applied using some shortcut that sets for it specially.

**Comment by unixzii** [comment]
Yep, it's a great feature proposal. We will add it later.

**Comment by WAY29** [comment]
I couldn't agree more, because it's a much better programming experience without a mouse

**Comment by Lirui-Zhao** [comment]
> Yep, it's a great feature proposal. We will add it later.

Oh there has another similar enhancement is using a shortcut to "Ask", maybe "Shift + Enter" or "Ctrl + Enter" are some good options
![image](https://user-images.githubusercontent.com/127711079/228422855-260e9731-163f-487d-9f93-90b03b3f7b03.png)

**Comment by unixzii** [comment]
> Oh there has another similar enhancement is using a shortcut to "Ask", maybe "Shift + Enter" or "Ctrl + Enter" are some good options

Will also be included in the next version.

**Comment by ktiays** [comment]
Hi @Lirui-Zhao, @WAY29. We added `Accept` and `Reject` as two commands. You can bind your favorite keyboard shortcuts to them manually.
